services:
  myfirstapp-web:
    image: nginx:latest
    container_name: myfirstapp-web
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  myfirstapp-app:
    image: php:8.3-fpm
    container_name: myfirstapp-app
    volumes:
      - ../src:/var/www/html
